# Site settings
title: Ipixel
email: Ipixel
description: > Ipixel help your bunsiness to grow, we work with Design, marketing and web sites
baseurl: ""
url: "https://www.ipixel.com"

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor/bundle
  - .gitignore
  - .editorconfig
  - Makefile


# Build settings
markdown: kramdown
