# Site settings
title: Ipixel
email: Ipixel
description: Ipixel help your bunsiness to grow
baseurl: ""
url: "https://www.ipixel.com"

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor/bundle
  - .gitignore
  - .editorconfig
  - Makefile

# Plugins
plugins:
  - jekyll-multiple-languages-plugin

# Build settings
markdown: kramdown

#Languages
languages: ["sv", "en", "ar"]
exclude_from_localizations: ["js", "img", "fonts", "css", "font-awsome"]
